package com.example.mymusic.presentation.util

object Constants {
    const val PLAYBACK_NOTIFICATION_CHANNEL_ID = "PLAYBACK_NOTIFICATION_CHANNEL_ID"
    const val PLAYBACK_NOTIFICATION_ID = 3249
    const val MEDIA_ROOT_ID = "MEDIA_ROOT_ID"
    const val START_MEDIA_PLAY_ACTION = "START_MEDIA_PLAY_ACTION"
    const val REFRESH_MEDIA_PLAY_ACTION = "REFRESH_MEDIA_PLAY_ACTION "
    const val PLAYBACK_UPDATE_INTERVAL = 1000L

}